# w1770946466 北慕白  https://github.com/w1770946466/Auto_proxy
# v2ray_collecto
# coding=utf-8
import base64
import requests
import re
import time
import os
import threading
from tqdm import tqdm
import random, string
import datetime
from time import sleep
import chardet

#试用机场链接
home_urls =(

'http://1.1596666.xyz',
'http://1.1598888.xyz',
'http://103.70.59.53',
'http://146.56.101.50',
'http://2983839.xyz',
'http://2ec535a5c35aa5a4b44249428dbb3d01.52pokemon.top',
'http://372ae8252c9ce608c5f7066f2177dfb1.52pokemon.top',
'http://52.moguyun.xyz',
'http://54.193.243.32',
'http://569cdn.1010520.click',
'http://6465307854ab0a2c82b66d32ffa2107e.52pokemon.top',
'http://66ds.dishujichang.xyz',
'http://6b.zhunchuanpb.com',
'http://6bsub.zhunchuanpb.com',
'http://a123.buzz',
'http://ant77.top',
'http://api.123417.xyz',
'http://api.aca.best',
'http://api.scyu.xyz',
'http://api.sgjc.xyz',
'http://api.wtcloud.xyz',
'http://api.xn--14ra41gd24b.xyz',
'http://api-0609.m55u97uleod7lm5.download',
'http://app2024.jieshiwangluo.com',
'http://beautyandbeast.link',
'http://best.momoxiaodian.cc',
'http://bp.wbno1.xyz',
'http://c9k.buzz',
'http://cdn.fastwork.cc',
'http://chaojiji.one',
'http://config.sled.autos',
'http://dashabi.ping-zi-yun.icu',
'http://dishujichang.xyz',
'http://dy.changyouVPN.top',
'http://dy.changyouvpn.top',
'http://dy.hpyjc.top',
'http://dy.silicloud.xyz',
'http://dy.xyyjc.top',
'http://e8a580bd3a51b6050aabd8919a17d106.52pokemon.top',
'http://ec2-13-215-48-59.ap-southeast-1.compute.amazonaws.com',
'http://em7.buzz',
'http://fanqiang88.top',
'http://fbapiv1.fbsublink.com',
'http://fdgdr0dg3.xbvpn.vip',
'http://feigou.zhunchuanpb.com',
'http://fs123121.cdn.22.jiacdnd123456789.com',
'http://gbtgurl01.org',
'http://ggiuwegivhe123.a123.bond',
'http://guguyun.xyz',
'http://hpyjc.top',
'http://jjz.31465.cfd',
'http://jshou.top',
'http://lafusees.com',
'http://laobideng.xyz',
'http://lianjiasub.work',
'http://ly.ccwink.cc',
'http://mf.kejifan88.top',
'http://mine.subcsyun.online',
'http://msvpn.gougouvpn.xyz:88',
'http://n15uvht4r659107p.eastasia.cloudapp.azure.com',
'http://nachoneko.cn',
'http://nangang.mom',
'http://on1vejas4m6z.w7yxefcx0i11.click',
'http://one.bblinks.top',
'http://panda.xn--i8sx78aisa52z.com',
'http://panda.xn--lbrx91akmhm30c.com',
'http://s.33y.run',
'http://s.kalaa.me',
'http://s1.subcsyun.online',
'http://s3.subcsyun.online',
'http://s4.subcsyun.online',
'http://saobiwang.top',
'http://sp.nfsq.me',
'http://sub.expmc.com',
'http://sub.sub.sub.subsub123456789.com',
'http://sub.xn--54qu5qypuo1o.xn--fiqs8s',
'http://sub1.efshop.cc',
'http://sub2086.fnyune.shop:2086',
'http://subs.202218.xyz',
'http://tuzi226.top',
'http://url.lx-cloud.xyz',
'http://user.dafeiji.one',
'http://user.tsunaminet.cc',
'http://v2.fkc99m.cfd',
'http://v2-1.806cms.top',
'http://vip.365cloud.me',
'http://vpn.gougouvpn.xyz:88',
'http://vps.huanshi88.sbs',
'http://www.chachajichang.top',
'http://www.crosswall.org',
'http://www.fanqiang88.top',
'http://www.freeflyingcloud.xyz',
'http://www.mmsbs.buzz',
'http://www.pingzicloud.top',
'http://xn--4gq62f8yih87b.site',
'http://xn--gmqa02ag57d.com',
'http://xn--mesx48ahb331x.com',
'http://xxxu.xyz',
'http://ya555.top',
'http://yy-cmi.mozhiti.top',
'http://yzxxy.top',
'https://01.laomao1.xyz',
'https://03.laomao1.xyz',
'https://04.laomao1.xyz',
'https://0415.chun-auto-one.xyz',
'https://06.laomao1.xyz',
'https://069059b7ef-1ytapi01.1ytsub.com',
'https://07.laomao1.xyz',
'https://08.laomao1.xyz',
'https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz',
'https://088EA81A-3547-85E0-4AF6-DFCB3C6674AA.372372.xyz',
'https://0918bde2-d3c6-354c-9919-672626903188.nginxtanz.click',
'https://0b96e976-9ec3-44c0-aa2b-30bf8b0792ea.com',
'https://0d2th.no-mad-world.club',
'https://0f36b897-2a77-3921-a2ca-3d1bb29fa8a5.ftqconfig.com',
'https://0mv.top',
'https://1.ayouok.online',
'https://1.baobaodeshanye.site',
'https://1.bethebest.eu.org',
'https://1.cutecloud.net',
'https://1.ovofast.xyz',
'https://1.xn--xc3ao8r.top',
'https://10th.sub-airport.com',
'https://11.laomao1.xyz',
'https://1122331.xyz',
'https://12.laomao1.xyz',
'https://12123.org',
'https://13.laomao1.xyz',
'https://1321078938-11mmjf3qkb-hk.scf.tencentcs.com',
'https://135841.xyz',
'https://14.laomao1.xyz',
'https://14ce7f2b-1b99-417c-ab7b-6de0d94baec8.apcdn.org',
'https://15.laomao1.xyz',
'https://16th.sub-airport.com',
'https://17.laomao1.xyz',
'https://17852.xyz',
'https://18.laomao1.xyz',
'https://196284.nginxzfd.xyz',
'https://1a1fe884-ae3c-3610-8075-cb778431f722.subdog.cyou',
'https://1milk.top',
'https://1st.sub-airport.com',
'https://1ytcom01.1yunti.net',
'https://2.maomaody.xyz',
'https://20.laomao1.xyz',
'https://20189999.xyz',
'https://2024.175698.xyz',
'https://20240802.canadapost-vip.com',
'https://209966.xyz',
'https://22.lownet.xyz',
'https://231787.xyz',
'https://25054128.xyz',
'https://3.feiniaoyun01.life',
'https://3.mimoe4.ru',
'https://30178aeb-8299-045d-fb67-ae12ce73dd2c.buou.lol',
'https://30388d70-6f5c-4d7c-8daa-9d3df7c5c526.9150e878-8296-4798-a172-c3fe66b8dee5.ddnsgeek.com',
'https://3093492f6b2332f8server.lycoris.one',
'https://32v.xyz',
'https://33.maoyun1.shop',
'https://333333.live',
'https://353g78qgfq.surfcat.store',
'https://38.181.25.67',
'https://3h.lv',
'https://4.jdy1027ue.lol',
'https://404.k6.gay',
'https://41be350f-5079-4195-8329-f6fa25f9906a.com',
'https://422.jcool.cool',
'https://4259f1e1-ff0e-461a-b7ff-c734d374eb68.shandiannginx.com',
'https://45bcb080ade759e2.cdn.jiashule.com',
'https://47.237.21.85',
'https://4e60bafd-0633-4e8d-a02a-eef51cd1ad8e.xn--mes358a.art',
'https://4gfree.asia',
'https://4th-subscription-from-chickenfarmer.top',
'https://4ulgur4.wuxianliuliang.cfd',
'https://5.52vpn.xyz',
'https://502dy.cloudoo.xyz',
'https://520.qjfjc.top',
'https://523qaweg246.pandafly.site',
'https://52daishu.uk',
'https://52niu.xyz',
'https://52pokemon.xz61.cn',
'https://548ff3c1-d8c8-3110-a65a-fb55573380c7.nginx24tanz.xyz',
'https://569cdn.1010520.click',
'https://57e6938f-92e3-3e4c-ad9d-6c8622486768.nginx24zfd.xyz',
'https://711.886511.xyz',
'https://7cd49968.nmsubs.com',
'https://7th-subscription-from-chickenfarmer.top',
'https://805678.xyz',
'https://8payj.no-mad-world.club',
'https://9527.bigbigwatermelon.com',
'https://98kjc.com',
'https://99ding.men',
'https://9th-subscription-from-chickenfarmer.top',
'https://a.1145149.xyz',
'https://a.aikllc.tech',
'https://a.fsyun.xyz',
'https://a.jiedianxielou.workers.dev',
'https://a.mtdwoodwork.com',
'https://a.qcsub.com',
'https://a.qcsub.top',
'https://a.s2cat.cc',
'https://a.sdwan.im',
'https://a.suixincloud.top',
'https://a.xn--mnqr2d776chcv.com',
'https://a01.wjyhalou.makeup',
'https://a1.8jiasu.com',
'https://a2.shidianban.top',
'https://a241219.888545.xyz',
'https://a76.aaa7.info',
'https://a94d418e-1898-42df-bcf2-d970a5f3a939.mysubsoft.com',
'https://aaa.us123.icu',
'https://aaa.yunduanjc.top',
'https://abqmygfu.mdssconfig.com',
'https://abyssvpnya.net',
'https://ac1f3b35-1d03-3a85-beab-258d8f23edc6.nginxdotu.xyz',
'https://ac59a7cd-11af-3e35-a098-b785688ec627.aliyunsub.com',
'https://a-cdn.b-cdn.net',
'https://acl.syyn.pw',
'https://acow.wtf',
'https://admin.xn--iiq451n.com',
'https://adtzwnkwqq.southeastasia.cloudapp.azure.com',
'https://ae86.235999.xyz',
'https://af078381-fcf9-457a-b03a-7bfaf506cd0b.xn--l6qx3lcvp58x.com',
'https://agit.ai',
'https://ahiddenmask.top',
'https://aicccc.top',
'https://aifun.trafficmanager.net',
'https://aigame.totwo.xyz',
'https://aiosjhdy.forbit-api.boats',
'https://airport.raloar.top',
'https://aliair.xyz',
'https://alpha.sagittarius-link.com',
'https://amatrixap.com',
'https://anydoor.xyz',
'https://aoop.top',
'https://ap.niaodi.top',
'https://ap.niubi.site',
'https://apexxy.top',
'https://api.911tg3rs.com',
'https://api.abyssyun.top',
'https://api.acaisbest.shop',
'https://api.aurapro.xyz',
'https://api.cn2.pw',
'https://api.dingyueapi.cc',
'https://api.dingyueddns.life',
'https://api.e687699.top',
'https://api.e986532.top',
'https://api.eflink.xyz',
'https://api.fenghuolun.xyz',
'https://api.flowercloud.xyz',
'https://api.fuckvps.net',
'https://api.fuckyun.cc',
'https://api.georgle.cyou',
'https://api.heima2u.com',
'https://api.hk03.fysub.com',
'https://api.ikuntool.com',
'https://api.inforun.work',
'https://api.ktcat.online',
'https://api.lendcloud.tech',
'https://api.meomiao.me',
'https://api.misakanet.buzz',
'https://api.nainiucloud.xyz',
'https://api.neigui.us.kg:443',
'https://api.nexconvert.com',
'https://api.nutbit-node.lat',
'https://api.oxygenproxy.top',
'https://api.pithecia.com',
'https://api.shin-x.top',
'https://api.ssrsub.com',
'https://api.sub-200.club',
'https://api.tshl.cc',
'https://api.tsutsu.one',
'https://api.wcc.best',
'https://api.wd-blue.com',
'https://api.wd-red.com',
'https://api.wtcloud.xyz',
'https://api.xinyo.vip',
'https://api.xjichang.buzz',
'https://api.xmancdn.net',
'https://api.xn--14ra41gd24b.xyz',
'https://api.xn--bnq37rc0nw50b.com',
'https://api.xn--yfr72t8r4bvhd.xyz',
'https://api.xqc.best',
'https://api.xyurl.site',
'https://api.ytoo.xyz',
'https://api.yuyan.vin',
'https://api.zuanshivpn.cn',
'https://api.zzzzzl.me',
'https://api03.cjpaoche.xyz',
'https://api1.441166.xyz',
'https://api1.xn--bnq37rc0nw50b.com',
'https://api2.mbo-xxx.top',
'https://api2.xn--bnq37rc0nw50b.com',
'https://api3.6yuan.top',
'https://api3.okaycloud.top',
'https://apidy.pqjc.site',
'https://apii.xqc.best',
'https://apinainiucloud.lat',
'https://api-subscribe.lycoris.cam',
'https://apiv1.v27qae.com',
'https://apiv2.lemongg.top',
'https://api-zz.xn--14ra41gd24b.xyz',
'https://app.100861234.xyz',
'https://app.cloudlion.me',
'https://app.gomeow.cloud',
'https://app.jisovpn.site',
'https://app.legeth.cc',
'https://app.lwjyj.com',
'https://app.mitce.com',
'https://app.zilihaijichang.top',
'https://aq.louwangzhiyu.xyz',
'https://artislg.com',
'https://artyun.top',
'https://as.saururus.ink',
'https://asa.lol',
'https://asa01.888545.xyz',
'https://asdasd.dashuai.one',
'https://asdf.888545.xyz',
'https://atacyun.yydsii.com',
'https://atomlantis.cloud',
'https://atom-sub.com',
'https://atong88.top',
'https://auth.newlikebooks.xyz',
'https://auto.mitce.com',
'https://awacloud.online',
'https://b.bbydy.org',
'https://b.jiedianxielou.workers.dev',
'https://b.xiaow.cc',
'https://b3b0549e-160e-495a-a528-cccf5148bc48.372372.xyz',
'https://babybus.gay',
'https://baipiao.monster',
'https://bajie.wiki',
'https://bakconntoserver.nuomi.info',
'https://bansub7.bplink.xyz',
'https://bansub8.bplink.xyz',
'https://base64.bigwatermelon.org',
'https://bav46z6c.nicecloud.win:8443',
'https://bava8u2znaj6bdzzjnfb.wgetcloud.online',
'https://bayoeorescentpossessicoanseparateuneforescenphocommitte.adoptangelaboradvacotionclwonthorughconfrmcompimentdeseertaltar.org',
'https://bb.aliyun.best',
'https://bb.jmvks.cn',
'https://bb.xn--pzypc.store',
'https://bbc1207.xn--49st2e1z0f.xn--55qx5d',
'https://bbc1207.广安霖.公司',
'https://bbjc.xyz',
'https://bdsafhh.yiyuanlx.cc',
'https://bengalj.com',
'https://best.momoxiaodian.cc',
'https://bigairport.party',
'https://bigairport-sixth-sub.top',
'https://bigairport-sub.top',
'https://bilivideo-cdn.bbxy-link.top',
'https://binggo.ty996.xyz',
'https://blueAir.colacloud.free.hr',
'https://board.imaodou.xyz',
'https://board.k6.gay',
'https://board.nsde.date',
'https://board.queqiao.online',
'https://board.queqiao-subscription.xyz',
'https://boou.colacloud.free.hr',
'https://bozhi.591haoka.com',
'https://bpjc.art',
'https://bpjc.lol',
'https://bptz.xyz',
'https://browser.networkwebmail.com',
'https://btepdc.lol',
'https://bujidao.cc',
'https://bunnyspeedox.online',
'https://c.jiedianxielou.workers.dev',
'https://c3.notesync.org',
'https://cainiao164.top',
'https://cainiaofit.cc',
'https://caoyyds.com',
'https://cat.ikkt.cn',
'https://cdcloud.b-cdn.net',
'https://cdn.1454250.xyz',
'https://cdn.fraternizey.com',
'https://cdn.legeth.com',
'https://cdn.naichayun.xyz',
'https://cdn.qfyun.me',
'https://cdn.wumaojichang.com',
'https://cdn-01.example.help.cn.faster.aliyuncdn.life',
'https://cdn1.xr56385d.qianglie.cloud',
'https://cdn1712594108.ppgnginx.com',
'https://cdn1715497317.ppgnginx.com',
'https://cdn1726062905.nginx24caiyun.xyz',
'https://cdnbao.foxi4.com',
'https://cdn-web-api.moeu.top',
'https://celerlink.buzz',
'https://centos.download-config-bit.cyou',
'https://ceshi.888451.xyz',
'https://cf.7854128.xyz',
'https://cf.buliangO.cf',
'https://cf.lemshow.top',
'https://cf.loveqyun.cyou',
'https://cfcloud.cyou',
'https://cfyun.top',
'https://cfyun01.sbs',

'https://changding.link',
'https://chaozhijc.xyz',
'https://checkhere.top',
'https://ck2.yunxiangvip.mom',
'https://clashfree.eu.org',
'https://client.cyberairport.work',
'https://client.fhlsep.cn',
'https://client-sub.cloudlion.top',
'https://cloud.anyijc.top',
'https://cloud.asdkd.top',
'https://cloud.chaozhijc.xyz',
'https://cloud.gomeow.tech',
'https://cloud.gyyun.top',
'https://cloud.inorym.one',
'https://cloud.jsfx.tech',
'https://cloud.luckilx.com',
'https://cloud.mochen.one',
'https://cloud.optionwiney.com',
'https://cloud.ykkk.tech',
'https://cloud.yydschina.top',
'https://cloud2.fanqiecloud.top',
'https://cloud3.fanqiecloud.top',
'https://cloud5.colacloud.site',
'https://cloudcat.top',
'https://cloudfisher.net',
'https://cloudflaresub.yuwan.link',
'https://cloudfront-cdn-hk-iplc1.com',
'https://cloudlion.me',
'https://cloud-port.xyz',
'https://cloudreve.top',
'https://cm.qc77.cn',
'https://cm-sub.pz.pe',
'https://cn.xn--iiq540h.com',
'https://cococloud.online',
'https://cokecloud.net',
'https://cola.xn--chqu2nzsxv3y.com',
'https://config.huojian111.com',
'https://coo.web.coo.wiki',
'https://csgo.fask511.cfd',
'https://csgo1.fask511.cfd',
'https://cshjc.xz61.cn',
'https://csicd782-isu.acyunv.buzz',
'https://csjc.xyz',
'https://csyun.t1csyun.shop',
'https://cyberguard.cfd',
'https://d.palu123.com',
'https://d.waka.plus',
'https://d01c076a.zjjjjyun.site',
'https://d1.dlsdist.net',
'https://d1to2me5cb4qc0.cloudfront.net',
'https://d2f42a86-2a1f-49b5-bd2f-d2154daa6a09.com',
'https://d3keb6jjtp861e.cloudfront.net',
'https://d7b12d59-21aa-9561-087f-89c834ac7fe8.372372.xyz',
'https://dadada.acaisbest.com',
'https://damp-mode-4de5.6006101.workers.dev',
'https://dash.djjc.cfd',
'https://dash.fengqunvpn.co',
'https://dash.fscloud.cc',
'https://dash.ftclashcloud.mom',
'https://dash.spcloud.info',
'https://dash.yfjc.xyz',
'https://datacenter_us.pithecia.com',
'https://datmicxg.mdssconfig.com',
'https://dawson0207.xn--3iq226gfdb94q.com',
'https://daxun.buzz',
'https://dd.moonriver.cfd',
'https://dd.xz61.cn',
'https://ddd.trc20.top',
'https://ddys.yunjisuan.cf',
'https://ddys.yunjisuan.gq',
'https://definitely.shota.wiki',
'https://df810594c639v.cloudfront.net',
'https://dfgsdfg.ghkjfgjkdfghrjfghjvbnm.cfd',
'https://didiaoshangwang.top',
'https://dingyue.097420.xyz',
'https://dingyue.cloudaccess.icu',
'https://dingyue.doushimeng.com',
'https://dingyue.starnetcn.com',
'https://dingyue.trojanws.xyz',
'https://dingyue.wenlianyun.vip',
'https://dingyue.xn--9kq09e124d.xyz',
'https://dingyue.xxss.org',
'https://dingyue1.b-cdn.net',
'https://dingyue2.doushimeng.com',
'https://dingyuea1d.naigai.me',
'https://dingyueieurwly.iajsy.lol',
'https://dj.taipeicity.news',
'https://djjc.cfd',
'https://dkcc71fg830ah.cloudfront.net',
'https://dl.owokkvsxks.store',
'https://dl.vfkum.website',
'https://doata.net',
'https://dogess.ink',
'https://doucat.top',
'https://douyun.sbs',
'https://duijie.cfyun.top',
'https://duijie.pingziyun.top',
'https://dump.facal.one',
'https://dy.alue.life',
'https://dy.beiyong.top',
'https://dy.chaozhijc.xyz',
'https://dy.csjc.win',
'https://dy.huidu718.com',
'https://dy.ikuai66.xyz',
'https://dy.jimao.icu',
'https://dy.jimaoyun.top',
'https://dy.justcn2.top',
'https://dy.kuailejc.xyz',
'https://dy.kunkun.v6.navy',
'https://dy.liuyingyun.work',
'https://dy.magicm.link',
'https://dy.naisicloud.xyz',
'https://dy.netfly.sbs',
'https://dy.nfsq.lol',
'https://dy.piaomiaoxu.com',
'https://dy.pmcloud.top',
'https://dy.pmxu.link',
'https://dy.pmxu.xyz',
'https://dy.qjfjc.top',
'https://dy.shandiandog.com',
'https://dy.smjc.top',
'https://dy.ssysub6.xyz',
'https://dy.tgmini.top',
'https://dy.ucat.live',
'https://dy.v-too.cloud',
'https://dy.xn--ehqx7tcnnope.live',
'https://dy.xn--mesx48ahb331x.com',
'https://dy.yh13.xyz',
'https://dy0.mmydy.xyz',
'https://dy001.maikcloud.top',
'https://dy001.sanxi.cyou',
'https://dy005.maikcloud.top',
'https://dy01.mmydy.xyz',
'https://dy01.nfsq.lol',
'https://dy1.hhyun.in',
'https://dy1.mmydy.xyz',
'https://dy-1.smjcdh.com',
'https://dy11.baipiaoyes.com',
'https://dy2.mmydy.xyz',
'https://dy3.yunhu1.xyz',
'https://dy4.feitudy.xyz',
'https://dy4.jdkys75.co',
'https://dy4.mmydy.xyz',
'https://dy5.baipiaoyes.com',
'https://dy5.feituyun.xyz',
'https://dy5.jdkys75.co',
'https://dy5.mmydy.xyz',
'https://dy6.mmydy.xyz',
'https://dy7.jdkys75.co',
'https://dy7.mmydy.xyz',
'https://dy8.feitudy.xyz',
'https://dy8.jdkys75.co',
'https://dy9.baipiaoyes.com',
'https://dy9.mmydy.xyz',
'https://dycd.gsjc.sbs',
'https://dycd.knjc.cfd',
'https://dydz.csjc.win',
'https://dyj.me',
'https://dylj.wanwan1024.top',
'https://dyvip.ianong.cn',
'https://dzpd.jiedianxielou.workers.dev',
'https://e1452652-32ee-b946-e3e7-d9be7070058e.buou.lol',
'https://easylink.space',
'https://easylink.work',
'https://edgeonereclaim.ikkt.cn',
'https://edu.dianping.men',
'https://edu.kuaifaka.me',
'https://eeeeehhhoyfhaihfg.qrfly.me',
'https://efxxl.xyz',
'https://eggtartcloud.biz',
'https://eggtartcloud.shop',
'https://ei2z64gntpgimmtw.duboji.vip',
'https://enetsub.egeturl.com',
'https://entrance.facmata.net',
'https://extc.shop',
'https://ez1.ezicloud.top',
'https://f1.feitudy.xyz',
'https://f3.feitudy.xyz',
'https://faf047da-5e7e-4da7-8414-2799d48ad63a.nginxcatnet.xyz',
'https://falcocloud.730894.xyz',
'https://fast.gfwstable.icu',
'https://fast.lycorisrecoil.org',
'https://fast.shiyuanyinian.xyz',
'https://fast1.baipiaoi489hy0p44ty.xyz',
'https://fastcloud.top',
'https://fastestcloud.xyz',
'https://fb.umgtb.cn',
'https://fbapiv2.fbsublink.com',
'https://feed.iggv5.com',
'https://feima.xn--fiqr3f3yq87hgq1c.com',
'https://feiniaoyun.life',
'https://feiniaoyun.top',
'https://feiniaoyun.xyz',
'https://feiniaoyun11.life',
'https://feitucloud.com',
'https://fengqunvpnvip.jmvks.cn',
'https://ff3a7d92-7568-4cca-a053-37087bee70b7.xn--mes358a.art',
'https://fgsfgs.12306.sbs',
'https://fhfdf.ghkjfgjkdfghrjfghjvbnm.cfd',
'https://flare089.sunyi.io',
'https://fly.puroc.cc',
'https://fly0001.buzz',
'https://flybit.pages.dev',
'https://flycnb.tk',
'https://flynb.site',
'https://fn1.170809.xyz',
'https://followcloud.space',
'https://forks.giegie.loan',
'https://free.andiliba.cc',
'https://free.cfnode.shop',
'https://free.colacloud.free.hr',
'https://free.kcjs.me',
'https://free.ninecloud.co',
'https://free.suwas.xyz',
'https://free.vpn66.eu.org',
'https://freeflyingcloud.com',
'https://fs.v2rayse.com',
'https://fs123121.cdn.22.jiacdnd123456789.com',
'https://fsc.jiediandingyuejiji.homes',
'https://fuqing.ch',
'https://fy6.2344599.xyz',
'https://fzdwz.top',
'https://g1.subjsm.cyou',
'https://gates.djjc.cfd',
'https://gateway.51tu.lol',
'https://gauss.life',
'https://gawrgura.moe',
'https://gbshct.spphhnhg.top',
'https://gbtgurl.me',
'https://get.biu001.xyz',
'https://get.ninesub.us.kg',
'https://getinfo.bigbigwatermelon.com',
'https://getinfo.bigwatermelon.org',
'https://gg2.hneko.buzz',
'https://ggiuwegivhe123.a123.bond',
'https://gist.githubusercontent.com',
'https://github.com',
'https://global.tagonline.asia',
'https://go.hhyun.in',
'https://go.yspeed.top',
'https://goodme.pro',
'https://gousstar.cloud',
'https://grslfa.clashx.app',
'https://gs.kkhhddnn.cn',
'https://gsjc.sbs',
'https://guanwang.me',
'https://guolicheng.cfd',
'https://gx.591haoka.com',
'https://gyyun.top',
'https://h.bbydy.org',
'https://hailitum.giountal.top',
'https://haitunyun.online',
'https://haohaoxuexi.qiao1.xyz',
'https://hela.ink',
'https://helloworld-gkhnaabtdcefa9d5.z01.azurefd.net',
'https://hh.haibucuo.xyz',
'https://hh.hnekoo.top',
'https://hneko.top',
'https://hongxingdl.club',
'https://hongxingdl.com',
'https://hongxingdl.love',
'https://host.api-baobaog.rest',
'https://host.ssrbox.com',
'https://hsaii.mejd.cn',
'https://htcmi-20240805.mozhiti.top',
'https://huahe.link',
'https://huaikhwang.central-world.org',
'https://huaxia.tcekx.cn',
'https://huaxia.wueh.cn',
'https://huaxiajichang.cc',
'https://hutaod.com',
'https://hx0618.xn--wqr30o34q.xn--io0a7i',
'https://hx1.starcloud.monster',
'https://hy-2.sbs',
'https://ierboryt.spphhnhg.top',
'https://ifaner.dd94wan.com',
'https://igdux.top',
'https://ihjlkbcueiwqnwior.duboji.vip',
'https://ikuajingbus.com',
'https://ikuntool.com',
'https://inangua.lwjyj.com',
'https://info.iic08924f5w3b65o.xyz',
'https://ins77.link',
'https://install.cdn-sd.xyz',
'https://is7si.cfd',
'https://itdog.cloud',
'https://itjustasub.net',
'https://itjustasub.shop',
'https://j2s.buzz',
'https://jaybest.one',
'https://jb.taipeicity.news',
'https://jc.bbx9527.xyz',
'https://jc.sux.lol',
'https://jc.wingsjiasu.link',
'https://jilu.uuvpn.xyz',
'https://jindoucloud.xyz',
'https://jindouyun88.life',
'https://jiumaojiu.jiumaojiu.net',
'https://jixingnetwork.sbs',
'https://jj.mikasajzy.dynv6.net',
'https://jlhcloud.us.kg',
'https://jmssub.net',
'https://jscr.b-cdn.net',
'https://jshou.top',
'https://jsjc.cfd',
'https://juanwang.site',
'https://juechenyun.top',
'https://juechenyun.xyz',
'https://jxpodzmq93s8etq0.wmcssw.org',
'https://k61kz.no-mad-world.club',
'https://kako.xn--fiq626gzzgkv2a.com',
'https://kalaame.b-cdn.net',
'https://kcssr.ink',
'https://ki.hello1.xyz',
'https://kiking1223.xn--49st2e1z0f.xn--55qx5d',
'https://kiking1223.xn--l6q948csgdz41ai1y.com',
'https://kitsch.xn--8stx8olrwkucjq3b.com',
'https://kkjiasu.top',
'https://kl05.ximicloud.net',
'https://knjc.cfd',
'https://knmvc.site',
'https://kobcloud.com',
'https://kobee.metatai.xyz',
'https://kob-xxkl.top',
'https://koumakan.quickline.top',
'https://ktmcloud.cloud',
'https://ktmcloud.club',
'https://ktmcloud.cool',
'https://ktmcloud.life',
'https://ktmcloud.link',
'https://ktmcloud.lol',
'https://ktmcloud.me',
'https://ktmcloud.men',
'https://ktmcloud.one',
'https://ktmcloud1.club',
'https://ktmurl.club',
'https://ktmurl.top',
'https://kuidingyue.xyz',
'https://kuromisubs.shop',
'https://l.dabai.in',
'https://l.db-link01.top',
'https://lai.sudiudiu.xyz',
'https://landiancc.me',
'https://leseyun.com',
'https://let.bnsubservdom.com',
'https://liangyuandian.club',
'https://liangyuandian.net',
'https://liangyuandian.xyz',
'https://liangyuandian1.com',
'https://lianjia.me',
'https://lianjiajichang.com',
'https://lianjiasub.work',
'https://lianjievpn.com',
'https://liljohnidc.store',
'https://limaiai.net',
'https://link.esnclink.com',
'https://link.kyjc.xyz',
'https://link.rstar.cloud',
'https://link01.fliggylink.xyz',
'https://link02.pikachucloud.site',
'https://link1.db01.in',
'https://link1.db-sub.xyz',
'https://link2.cccc.gg',
'https://link2.proxylink.xyz',
'https://link4.proxylink.xyz',
'https://link5.proxylink.xyz',
'https://linkcube.xyz',
'https://linke.phantasy.life',
'https://liulangdiqiu.cc',
'https://lizhiabc.xyz',
'https://llcool.net',
'https://llgjc.shop',
'https://lmaff01.lmspeed.co',
'https://login.681688.xyz',
'https://login.91unicorn.cc',
'https://login.djjc.cfd',
'https://login.yfjc.xyz',
'https://lonan.sirenyun.me',
'https://lovetalk.tech',
'https://luonan.tech',
'https://ly.ccwink.cc',
'https://lzyjc.xyz',
'https://lzysub.online',
'https://m.o29o.xyz',
'https://m11.spwvpn.com',
'https://m2net.lol',
'https://m2net.sbs',
'https://m33.spwvpn.com',
'https://mac2winer.cfd',
'https://magicae.pics',
'https://maple.icu',
'https://md.tagsub.cf',
'https://mdzz.nmsl.cnmd.ttiktokvpn.top',
'https://meiyiss1.yccch03.top',
'https://meoovpn.net',
'https://meowport.link',
'https://mercedes1208.xn--3iq226gfdb94q.com',
'https://miserableskeletalcpu--jiushinali4.repl.co',
'https://mitce.com',
'https://mlshu.com',
'https://mlshu.xyz',
'https://mo.mojieurl.com',
'https://mochizuki.top',
'https://mojie.app',
'https://mojie.art',
'https://mojie.best',
'https://mojie.co',
'https://mojie.link',
'https://mojie0201.xn--8stx8olrwkucjq3b.com',
'https://mrdoudou.xyz',
'https://mro5n.no-mad-world.club',
'https://msio.uk',
'https://mtf.lat',
'https://muacloud3.live',
'https://muguacloud.top',
'https://muniu.click',
'https://muniu.ink',
'https://music.easygourl.xyz',
'https://mxcsir.cc',
'https://my.335570.xyz',
'https://my.cat66.lol',
'https://my.catfaka.com',
'https://my.mingri.icu',
'https://my.pathx.me',
'https://mybear.xyz',
'https://mydy.xlm.plus',
'https://myko.buzz',
'https://mymy.lanyanyun.co',
'https://mysub.cc',
'https://mytoken.huyun.nl',
'https://mytoken-1.huyun.nl',
'https://myu.best',
'https://n3.leensasub.net',
'https://n3.leensasub.us',
'https://nachoneko.azurefd.net',
'https://nachoneko.cn',
'https://naikosub.com',
'https://naixisub.com',
'https://naiyun0315.xn--8stx8olrwkucjq3b.com',
'https://nanbei.cloud',
'https://nanbei.cyou',
'https://nangang.mom',
'https://nano.nachoneko.cn',
'https://nanoport.azurefd.net',
'https://needay.net',
'https://needay.xyz',
'https://nekocandy.pages.dev',
'https://neo.facal.one',
'https://neoconf.net',
'https://neolink.nkkc.one',
'https://net.17181922.xyz',
'https://net.virtualschool.cc',
'https://netstar.vip',
'https://nexuscloud.ch',
'https://nexuscloud.xyz',
'https://nfsq.nfsq.me',
'https://niaodi.top',
'https://nicewy.xyz',
'https://niceyun.xyz',
'https://ninjasub.com',
'https://nmsubs.com',
'https://nn0310.xn--8stx8olrwkucjq3b.com',
'https://nn8qozmu.nn8qozmu.top',
'https://node.666666222.xyz',
'https://node.reami.us',
'https://node.yifang02.men',
'https://node.zasublinkv1.com',
'https://nogin.djjc.cfd',
'https://noproblem.eu.org',
'https://notls.11111111.eu.org',
'https://num.763352.top',
'https://nuonuonet.uk',
'https://official.b-cdn.net',
'https://oiiccdn.yydsii.com',
'https://on1vejas4m6z.w7yxefcx0i11.click',
'https://onlysub.mjurl.com',
'https://openui.n256.com',
'https://oss.pithecia.com',
'https://oss.v2rayse.com',
'https://oss-alibabaclod.fsddsadsavgroup.top',
'https://outofthisworld.dropyourlove.top',
'https://ovofast.xyz',
'https://p2.magicyun.online',
'https://panel.kelecloud.xyz',
'https://panel.quickv2.com',
'https://pastebin.mozilla.org',
'https://pathx.me',
'https://pavo.eu.org',
'https://pfjc.im',
'https://pianyi.sub.sub.subsub123456789.com',
'https://pincht.sbs',
'https://platform.djjc.cfd',
'https://porkbun.cc',
'https://portal.karleynetwork.shop',
'https://portal.meomiao.xyz',
'https://post.jianjiaoyun.link',
'https://pqjc.site',
'https://pro.76898102.xyz',
'https://pro.xn--l9qyaz082a.cn',
'https://prob.xn--l9qyaz082a.cn',
'https://proc.xn--l9qyaz082a.cn',
'https://protal.xfxun.com',
'https://proxyinfo.net',
'https://pziv7.xiaoliyu.xyz:8443',
'https://qgyun.cc',
'https://qhcy.cc',
'https://qifei.today.elementfx.com',
'https://qingchayun.icu',
'https://qkt83qnp2yuj.subconnect.org',
'https://qq.xlm.plus',
'https://QTjDQsor6e7D.configbit.com',
'https://qwerzfdsfgrtds.mejd.cn',
'https://qyoo.aibvs.cn',
'https://raw.githubusercontent.com',
'https://reimu-tools.102498.xyz',
'https://renovpn.pro',
'https://rgergergergerg6555.saojc.xyz',
'https://rk.wuxianliulianng.xyz',
'https://rk.wxlljc520.com',
'https://robinxxx.xyz',
'https://rss.biteb-sub.com',
'https://rss.paoluz.xyz',
'https://rss2.jkl-sub.com',
'https://rss2024.jkl-sub.com',
'https://rss202407.mugua-sub.com',
'https://rsslinghun1.xyz',
'https://rss-node.com',
'https://run-s2.jiedianxielou.workers.dev',
'https://s.feisucloud.xyz',
'https://s.haituncloud.vip',
'https://s.hajimi.icu',
'https://s.jiasu01.vip',
'https://s.jockerchief.online',
'https://s.juzicloud.vip',
'https://s.kalaa.me',
'https://s.sdfjwlkcwoiwefcmslk2csaadskl.xyz',
'https://s.sdncimcin.xyz',
'https://s.suying666.info',
'https://s.youyun666.site',
'https://s.yyme.me',
'https://s1.bnpublicsub.com',
'https://s1.bnsubservdom.com',
'https://s1.byte16.com',
'https://s1.byte33.com',
'https://s1.iajsy.lol',
'https://s2.equinoxaa.com',
'https://s3.iajsy.lol',
'https://s3.taoqitu.lol',
'https://s4.iajsy.lol',
'https://s6.ssysub1.xyz',
'https://s7.sub.gfw.gg',
'https://sailingsub.icu',
'https://sakuracat1203.xn--3iq226gfdb94q.com',
'https://sanfen002.xyz',
'https://sanfen003.xyz',
'https://sanfen005.xyz',
'https://sanguayun.jiumaojiu.net',
'https://saobiwang.top',
'https://sb.meslcloud.com',
'https://sb.swiftnet.cloud',
'https://sbs.fastfly.life',
'https://sbs.fastfly.life:21600',
'https://sbsqwzfgh.santoku.cn',
'https://sc.ubs.dynuddns.com',
'https://sdgvps.com',
'https://sdkdns3.com',
'https://sds2.ergou168.info',
'https://server.fylink.link',
'https://service-472jprl5-1322266764.sh.apigw.tencentcs.com',
'https://service-69kfaex1-1312645837.bj.apigw.tencentcs.com',
'https://service-6l9168iy-1312645837.gz.apigw.tencentcs.com',
'https://service-avmn443l-1312645837.sh.apigw.tencentcs.com',
'https://service-bmp1m9zg-1312645837.nj.apigw.tencentcs.com',
'https://service-e6np5k91-1312645837.sh.apigw.tencentcs.com',
'https://service-fy4hli0a-1312645837.nj.apigw.tencentcs.com',
'https://service-o5lxqvaa-1300544878.gz.apigw.tencentcs.com',
'https://sgcloud.icu',
'https://shadowpocket.site',
'https://shanchuixing.com',
'https://shandiandog.com',
'https://shellclash.svaccaro307.workers.dev',
'https://sinsocloud.top',
'https://sirenyun.me',
'https://site.bzqjc.top',
'https://skrspc.com',
'https://smjc.shop',
'https://snangua.com',
'https://sockboom.me',
'https://sp.nfsq.me',
'https://sq9xy6.cpminig.com',
'https://ss.2b2.top',
'https://ss.81dlg.com',
'https://ss.cft.my',
'https://ss.hxcq.cc',
'https://ss.suyunti.cc',
'https://sspsubs.trafficmanager.net',
'https://sss.xn--4gqt91ntld.space',
'https://ssvpn.org',
'https://starlinkcloud.club',
'https://starlinkcloud.life',
'https://starlinkcloud.org',
'https://starlinkcloud.xyz',
'https://store.kakocloud.pro',
'https://st-sub.fly.dev',
'https://study.jaycloud11111.top',
'https://study1.v1999.sbs',
'https://su.xfjhchr.com:8888',
'https://sub.19993999.xyz',
'https://sub.372372.xyz',
'https://sub.591haoka.com',
'https://sub.669977.xyz',
'https://sub.abcdefghijklmnopqrstuvwxyz1234567890.xyz',
'https://sub.alice.sale',
'https://sub.andaofu.xyz',
'https://sub.apislave.com',
'https://sub.authapi.download',
'https://sub.bailian.site',
'https://sub.baozinet.top',
'https://sub.bbjc.xyz',
'https://sub.bigdong.top',
'https://sub.cdcloud.mingri.icu',
'https://sub.changding.link',
'https://sub.chasing.sbs:21600',
'https://sub.cjcloud.cc',
'https://sub.cloudlion.me',
'https://sub.cloudog.us.kg',
'https://sub.cnkizzc.eu.org',
'https://sub.cokecloud.world',
'https://sub.coo.ga',
'https://sub.dawanqukun.top',
'https://sub.dinastio.cc',
'https://sub.domiw.com',
'https://sub.download-hiccup.xyz',
'https://sub.dukadi.one',
'https://sub.dwlei.com',
'https://sub.extc.shop',
'https://sub.eyujichang.com',
'https://sub.feiji.ddns-ip.net',
'https://sub.feiji.ip-ddns.com',
'https://sub.fnf.one',
'https://sub.fnf.xyz',
'https://sub.gomeow.online',
'https://sub.gougou.live',
'https://sub.hktix.net',
'https://sub.hx666.pro',
'https://sub.hycloud.shop',
'https://sub.jbok.cc',
'https://sub.jdueloi0982.xyz',
'https://sub.jileiyun.top',
'https://sub.jileiyun.us.kg',
'https://sub.jsy88.net',
'https://sub.jsydy.xyz',
'https://sub.kaolacloud.site',
'https://sub.lingche.icu',
'https://sub.lly.cz',
'https://sub.lyunsub.win',
'https://sub.lzyjc.xyz',
'https://sub.marsix.cc',
'https://sub.mianfeiyun.online',
'https://sub.miaolianyun.vip',
'https://sub.miaosusub.cfd',
'https://sub.miku.llc',
'https://sub.milkcloud.org',
'https://sub.minizz.online',
'https://sub.mogufan.com',
'https://sub.mutoujd.top',
'https://sub.narutos.link',
'https://sub.nex7.us.kg',
'https://sub.no626.link',
'https://sub.nodeup.top',
'https://sub.oaahack.com',
'https://sub.ouoboom.xyz',
'https://sub.paasmi.com',
'https://sub.pianyi.info',
'https://sub.piercecloud.org',
'https://sub.porter6.eu.org',
'https://sub.qingfengyun.icu',
'https://sub.quanstring.top',
'https://sub.riolu.link',
'https://sub.sanfen007.xyz',
'https://sub.sanfen008.xyz',
'https://sub.sanfen010.xyz',
'https://sub.sanfen014.xyz',
'https://sub.sanfen017.xyz',
'https://sub.sanfen018.xyz',
'https://sub.sanqianlijinxiuheshan.us.kg',
'https://sub.sharecentre.online',
'https://sub.sheepcloud.xyz',
'https://sub.speed17sub.com',
'https://sub.speeddy.xyz',
'https://sub.sqfly.site',
'https://sub.ss888.tw',
'https://sub.sslinks.co.in',
'https://sub.ssr.sh',
'https://sub.ssrsub.com',
'https://sub.starnetcn.com',
'https://sub.surfcloud.ink',
'https://sub.taco.homes',
'https://sub.tangping.cloud',
'https://sub.texo.network',
'https://sub.tianmaojichang.us.kg',
'https://sub.tku2.com',
'https://sub.tuanzi.site',
'https://sub.tuanzi.xyz',
'https://sub.tudou213.com',
'https://sub.unolink.ink',
'https://sub.viefast.vn',
'https://sub.vpntz.com',
'https://sub.vvcloud.us.kg',
'https://sub.white.pp.ua',
'https://sub.wl-sub1.com',
'https://sub.wmcdn.top',
'https://sub.wordvlog.link',
'https://sub.wukong.bond',
'https://sub.xiaomf.store',
'https://sub.xinyo.vip',
'https://sub.xn--14ra41gd24b.xyz',
'https://sub.xn--4gq62ffxz.net',
'https://sub.xn--4gqp1u.com',
'https://sub.xn--9kqt24a0kz.com',
'https://sub.xn--9kqu5y58a.com',
'https://sub.xn--iiq540h.com',
'https://sub.xn--mesv7f5toqlp.com',
'https://sub.xsus.io',
'https://sub.xsus.me',
'https://sub.xttlove.uk',
'https://sub.xunicard.cc',
'https://sub.xunlian.site',
'https://sub.yifenjichang.online',
'https://sub.yihaojichang.xyz',
'https://sub.yiri.dev',
'https://sub.yiri.org',
'https://sub.yspeeds.uk',
'https://sub.yun.cat',
'https://su-b.yun.cat',
'https://sub.yuwan.link',
'https://sub.yxhc.date',
'https://sub.yztcloud.moe',
'https://sub.zjf2610.cn',
'https://sub-01.767564.xyz',
'https://sub01.jishu168.xyz',
'https://sub1.114514000000.xyz',
'https://sub1.bbjc.xyz',
'https://sub1.caiyun.nl',
'https://sub1.efshop.cc',
'https://sub1.globalforvpn.xyz',
'https://sub1.haiqilai.lol',
'https://sub1.huy.0.srl',
'https://sub1.jiatelin.cyou',
'https://sub1.ktyyun.com',
'https://sub1.liangxinjichang.com',
'https://sub1.mlcat.tk',
'https://sub1.smallstrawberry.com',
'https://sub1.tg-mfjd666.cloudns.be',
'https://sub1.timeneverchanges.com',
'https://sub1.twoyuanfun.online',
'https://sub1.yljc.online',
'https://sub123.71345.xyz',
'https://sub17621.xn--mes13h09douj.com',
'https://sub2.bighneko.top',
'https://sub2.download-hiccup.xyz',
'https://sub2.smallstrawberry.com',
'https://sub2.yljc.online',
'https://sub2038.kaochangsubscribe.xyz',
'https://sub3.hanghai.xyz',
'https://sub3.huy.0.srl',
'https://sub3.jie-quick.buzz',
'https://sub3.magicby.top',
'https://sub3.mi.huy.ooo',
'https://sub3.smallstrawberry.com',
'https://sub3.tnetvpn.com',
'https://sub3.xn--mes13h09douj.com',
'https://sub3.yljc.online',
'https://sub3.yunanyun.xyz',
'https://sub4.91qaq.lol',
'https://sub4.bbjc.xyz',
'https://sub4.download-hiccup.xyz',
'https://sub4.gfw.gg',
'https://sub4.haiqilai.lol',
'https://sub4.huy.0.srl',
'https://sub4.yljc.online',
'https://sub4.yunanyun.xyz',
'https://sub5.gfw.gg',
'https://sub5.huy.0.srl',
'https://sub6.xn--mes13h09douj.com',
'https://sub7.huy.0.srl',
'https://suba.lingche.icu',
'https://sub-api.fengcheyun.fun',
'https://sub-api.seeu-u.com',
'https://subcdn.cos.cat',
'https://sub-gfwairport2.cyou',
'https://sub-go.xqxa.xyz',
'https://subhiddify.mmdv2.host',
'https://sublink.52cloud.eu.org',
'https://submit.xz61.cn:23443',
'https://subneko.v1999.sbs',
'https://subo.starnetcn.com',
'https://subone.xyjc.xyz',
'https://subpanghujichang.xn--y20az5i.xyz',
'https://subs.pithecia.com',
'https://subs.usero.cn',
'https://subs.zeabur.app',
'https://subscr.b-cdn.net',
'https://subscribe.cloudlion.top',
'https://subscribe.fastsocks.xyz',
'https://subscribe.hio.best',
'https://subscribe.insidergame.xyz',
'https://subscribe.speedypro.xyz',
'https://subscribe.suwas.xyz',
'https://subscribe.tuboshu.bet',
'https://subscribe.v2ray.team',
'https://subscribe.wujielink.com',
'https://subscribe.xsus.net.co',
'https://subscribe.xttlove.uk',
'https://subscribe.ztpxxx.com',
'https://subscribe2628.lanmaoyun.icu',
'https://subscribe3.000000online.life',
'https://subscribe511295.fengqun.info',
'https://subscribe-ezz.ezicloud.top',
'https://subscribe-ezz.wyywyywyyonline.top',
'https://subscription.1238520.xyz',
'https://subscription.slshenlong.top',
'https://subscription-gov.lianjiasub.work',
'https://subscriptionruc.slshenlong.top',
'https://subserver.maying.io',
'https://subsubsubsubsub.keledydz.uk',
'https://subtest.mojc.xyz',
'https://subthree.996yyds.xyz',
'https://sub-xsus.com',
'https://sulian.life',
'https://sus.alicenetwork.cloud',
'https://suscribethenetword.beecloud.club',
'https://svip.365cloud.me',
'https://swiftnet.wiki',
'https://syyn.ianong.cn',
'https://syyn.xyz',
'https://syynweb.xyz',
'https://szdol.com',
'https://tagcdnsub.com',
'https://tagcdnsub.work',
'https://tagsub.cf',
'https://taibai0201.xn--8stx8olrwkucjq3b.com',
'https://takeshi.wiki',
'https://taoyuanjiasu.com',
'https://tcxf.hssl8088.icu',
'https://teddytales.love',
'https://tencentapi.wdycenter.com',
'https://testgo.kakocloud.pro',
'https://tg.z-cloud.dynv6.net',
'https://thepoint1.free886.site',
'https://tigercloud.club',
'https://time1721057549.nginxcaiyun.xyz',
'https://tizioo11.top',
'https://tjjd.yzyx1.v6.army',
'https://tokenapi.fbcloud.lol',
'https://toting.top',
'https://tr.gogdog.xyz',
'https://trieublack4g.com',
'https://trojan.gojw.net',
'https://truenet.cloud',
'https://ttc01.xyz',
'https://ttcloud.xyz',
'https://tudou.igken.com',
'https://tugeda.xyz',
'https://tv.modemhub.work',
'https://two.mojieurl.com',
'https://tz.vfkum.website',
'https://tzyy.link',
'https://tzyy1.tzyy.link',
'https://update.glados-config.com',
'https://update-debian.config-catnet.xyz',
'https://upm8kfu.nicecloud.win:8443',
'https://url.v1.mk',
'https://us.freecat.cloud',
'https://user.dafeiji.one',
'https://user192.dukadi.one',
'https://user413.dukadi.one',
'https://user9125.eyudy.one',
'https://v.131jsq.com',
'https://v.spwvpn.com',
'https://v1.chaojiji.one',
'https://v1.dogapi.yachts',
'https://v1.efshop.cc',
'https://v1.mk',
'https://v2.666119.xyz',
'https://v2.dogapi.yachts',
'https://v2.ixlmo.com',
'https://v2.ixlmo.net',
'https://v2.mugua-sub.com',
'https://v2.pikachu.cyou',
'https://v2.porter6.eu.org',
'https://v2.silverjie.buzz',
'https://v2.udid8.com',
'https://v2.zwtg888.com',
'https://v2b.cumslut.icu',
'https://v2b.hinetlove.site',
'https://v2b.n20.top',
'https://v2bapi.qhcy.me',
'https://v2board.dh556.shop',
'https://v2rayshare.com',
'https://v2y.xyz',
'https://v3.dogapi.yachts',
'https://v4.dogapi.yachts',
'https://vaet.xyz',
'https://vip.365cloud.me',
'https://vip.sgjc.top',
'https://vipma.top',
'https://vips.lol',
'https://vipxgyun.com',
'https://vodfavor.top',
'https://vot.278986.xyz',
'https://vot.689861.xyz',
'https://vot.981176.xyz',
'https://vpn.209966.xyz',
'https://vpn.jsvpn.xyz',
'https://vpn.linuxdo.pro',
'https://vpn6688.com',
'https://vt.louwangzhiyu.xyz',
'https://vtwoc1.top',
'https://vtwoc3.top',
'https://vyyy.vyunyunnode.top',
'https://wangdazhuang.top',
'https://wap.nnpy.org',
'https://watch.szlatteart.com',
'https://wcsjc.cloud',
'https://wd.vovo.pp.ua',
'https://web.coo.wiki',
'https://web888.naixue222.com',
'https://web888.naixue222.net',
'https://webget.yfjc.xyz',
'https://webridge.pokeryun.link',
'https://wg03u.no-mad-world.club',
'https://widget.yfjc.xyz',
'https://wly312.buzz',
'https://wm01dy.wmyun.men',
'https://wnbo.dev',
'https://wogame.dev',
'https://wow.dogss-host.bond',
'https://wow.dogss-host.store',
'https://wtkmk.naixiyun.top',
'https://wumao.jiumaojiu.net',
'https://wumaojichang.com',
'https://wvw.guanxi.cloudns.be',
'https://ww3.xn--mesv7f5toqlp.icu',
'https://wwe.trx1.cyou',
'https://wwm.huaxiamax.icu',
'https://wws.s2fjeyeeyafe.bond',
'https://www.02er.com',
'https://www.066664.xyz',
'https://www.360vpn.org',
'https://www.998877.best',
'https://www.airpor.top',
'https://www.antlink.cc',
'https://www.as41378.com',
'https://www.awa520.cloud',
'https://www.baiyunvpn.xyz',
'https://www.bitduct.net',
'https://www.bptz.xyz',
'https://www.bqg888.com',
'https://www.buffcloud.icu',
'https://www.bydk.xyz',
'https://www.catssr.top',
'https://www.catssr.xyz',
'https://www.ccsub.online',
'https://www.ccsub.org',
'https://www.celerlink.buzz',
'https://www.chaojijichang.com',
'https://www.ckcloud.xyz',
'https://www.cloudff.top',
'https://www.cloudshops.xyz',
'https://www.crosswall.org',
'https://www.csyyds.xyz',
'https://www.cwy-water.us.kg',

'https://www.dafei8.xyz',
'https://www.dbtop.top',
'https://www.dma.icu',
'https://www.efcloud.bio',
'https://www.elinksapi.com',
'https://www.fdzdk.xyz',
'https://www.fenglanpavilion.com',
'https://www.flyintpro01.com',
'https://www.flyintpro05.com',
'https://www.freeflyingcloud.xyz',
'https://www.ginfem.com',
'https://www.gogocloud.icu',
'https://www.itonlyasub.xyz',
'https://www.jafiyun2023.shop',
'https://www.jindoucloud.xyz',
'https://www.jinglongyu.com',
'https://www.kuaidog001.top',
'https://www.kuaidog008.top',
'https://www.kuaigou.life',
'https://www.landfill.top',
'https://www.laoniu49.top',
'https://www.lbxjc.online',
'https://www.liangyuandian.at',
'https://www.liangyuandian.life',
'https://www.lifenot.com',
'https://www.lineinchina-enterprise.tw',
'https://www.louwangzhiyu.xyz',
'https://www.luronn.com',
'https://www.m2net.cc',
'https://www.miyun.me',
'https://www.mojie.cool',
'https://www.moonriver.sbs',
'https://www.nertron.net',
'https://www.otcopusapp.cc',
'https://www.paofusub2.com',
'https://www.paopaotou.club',
'https://www.pdda.me',
'https://www.pddc.me',
'https://www.pkqcloud.com',
'https://www.qiaoxbbq.com',
'https://www.qilin2.com',
'https://www.qlgq.top',
'https://www.sofastcloud.com',
'https://www.sosoquick.com',
'https://www.sstank.top',
'https://www.tannel.xyz',
'https://www.tcip.top',
'https://www.tencloud.net',
'https://www.tianxianbaby.com',
'https://www.v2ny.one',
'https://www.v2youzi.top',
'https://www.vtwoc4.top',
'https://www.wexgc.com',
'https://www.xingsa.xyz',
'https://www.xingsu.club',
'https://www.xingsu.lol',
'https://www.xingsu.shop',
'https://www.xmfsubscribe.com',
'https://www.xn--30q31nc3o033b.com',
'https://www.xn--5hqx9equq.org',
'https://www.xn--9kq89dn23b.top',
'https://www.xn--gmq47msybdu2a.com',
'https://www.xzyunjiasu.com',
'https://www.yiyuanjichang.net',
'https://www.yutu.pw',
'https://www16.bigairport-eleventh-sub.top',
'https://www6.1st-subscription-from-chickenfarmer.top',
'https://www6.2nd-subscription-from-chickenfarmer.top',
'https://www8.6th-subscription-from-chickenfarmer.top',
'https://wwwjs.pro',
'https://x.nsa.cc',
'https://xb.bydk.xyz',
'https://xb.feiyi.mom',
'https://xb1.nets.pp.ua',
'https://xboard.sswiwi.com',
'https://xboard.texo.network',
'https://xfsnet.com',
'https://xfx.ink',
'https://xgjs1.cc',
'https://xgk8k4s.xiaoliyu.xyz:8443',
'https://xianyuwangluo.cc',
'https://xianyuwangluo.vip',
'https://xn--04s765d.net',
'https://xn--04s765d.site',
'https://xn--14ra41gd24b.xyz',
'https://xn--2dk290r.xn--p8jhn1a2d1epgoe.com',
'https://xn--4csqex52cft0a.com',
'https://xn--4gq62f52g.com',
'https://xn--4gq62f66mcsc.com',
'https://xn--4gqw1khydd1v.com',
'https://xn--4gqx1h.xyz',
'https://xn--7or611i.xyz',
'https://xn--94q649dc94a.com',
'https://xn--9kq147c4p2a.com',
'https://xn--9kqw7o.com',
'https://xn--ciq7ko0lg8x.xn--mes358avi4ba.xyz',
'https://xn--cp3a08l.com',
'https://xn--dqrs61a.xn--nyq8xnau43mp3cg06appat33dzol.xn--fiqs8s',
'https://xn--fhqu06a8m1asto.icu',
'https://xn--mes53ddysu0o3gl.top',
'https://xn--mes91r2ng7p4a.com',
'https://xn--mesr8b36xr0o.com',
'https://xn--mesv7f5toqlp.com',
'https://xn--mesz9ptugxg.com',
'https://xn--pbt777k.art',
'https://xn--pssq69d.xyz',
'https://xn--rgv465a.xyz',
'https://xnthqr2kqvdd1vchs.xyz',
'https://xn--thqr2kqvdd1vchs.xyz',
'https://xn--vpn-rw7eh25o.com',
'https://xn--vuqy45c.top',
'https://xn--wlqw2sc0nwqq.xyz',
'https://xn--xc3ao8r.live',
'https://xn--z7q48k8ya184b1ug.com',
'https://xquig3.youxuan.wiki',
'https://xs.mashiroshina.top',
'https://xsj520.top',
'https://xsus.moe',
'https://xsus.wiki',
'https://xunlei-api.okay.casa',
'https://xxjsm.xn--nrqu89ap6f632c.xn--io0a7i',
'https://xxxu.xyz',
'https://y4ckkxagxaxxefca.duboji.vip',
'https://ycgo.rabbit77.top',
'https://ydapi.dingyuetot.vip',
'https://yes1.xn--mesv7f5toqlp.xyz',
'https://yfjc.cfd',
'https://yh.acyun.tk',
'https://yingwuyun.vip',
'https://yiyolink.xyz',
'https://ykeji.xyz',
'https://ym.ksjhaoka.com',
'https://ymjc.cfd',
'https://ymzx.jiedianxielou.workers.dev',
'https://youxiu5172.xiaofeixia.cfd',
'https://youxiu7540.xiaofeixia.click',
'https://youxiu8168.xiaofeixia.info',
'https://ysjc.us.kg',
'https://yt.xn--49sq15btnijvp.xn--fiqs8s',
'https://yunlu.jiumaojiu.net',
'https://yuyun.yuyun.one',
'https://yyds.emovpn.top',
'https://yydsvpn.ml',
'https://yysw.acyun.tk',
'https://z.album.icu',
'https://z.playddt.com',
'https://z.upk.icu',
'https://zero.76898102.xyz',
'https://zhenshihui.shop',
'https://zhenxunkeai.top',
'https://zhongzhuan.mxmxmx.lol',
'https://zhuiyun.shop',
'https://zjsub.gitpub.top',
'https://zlxz.80jm.com',
'https://zouma.guanhua.xyz',
)
#文件路径
update_path = "./sub/"
#所有的clash订阅链接
end_list_clash = []
#所有的v2ray订阅链接
end_list_v2ray = []
#所有的节点明文信息
end_bas64 = []
#获得格式化后的链接
new_list = []
#永久订阅
e_sub = ['']
#频道
urls =[]
#线程池
threads = []
#机场链接
plane_sub = ['']
#机场试用链接
try_sub = []
#获取频道订阅的个数
sub_n = -25
#试用节点明文
end_try = []

#获取群组聊天中的HTTP链接
def get_channel_http(url):
    headers = {
        'sec-ch-ua': '".Not/A)Brand";v="99", "Google Chrome";v="103", "Chromium";v="103"',
        'Accept': 'application/json, text/javascript, */*; q=0.01',
        'Referer': 'https://t.me/s/oneclickvpnkeys',
        'X-Requested-With': 'XMLHttpRequest',
        'sec-ch-ua-mobile': '?0',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36',
        'sec-ch-ua-platform': '"Windows"',
    }
    response = requests.post(
        url, headers=headers)
    #print(response.text)
    pattren = re.compile(r'"https+:[^\s]*"')
    url_lst = pattren.findall(response.text)
    #print('获取到',len(url_lst),'个网址')
    #print(url_lst)
    return url_lst


#对bs64解密
def jiemi_base64(data):  # 解密base64
    # 对 Base64 编码后的字符串进行解码，得到字节字符串
    decoded_bytes = base64.b64decode(data)
    # 使用 chardet 库自动检测字节字符串的编码格式
    encoding = chardet.detect(decoded_bytes)['encoding']
    # 将字节字符串转换为字符串
    decoded_str = decoded_bytes.decode(encoding)
    return decoded_str

#判读是否为订阅链接
def get_content(url):
    #print('【获取频道',url,'】')
    url_lst = get_channel_http(url)
    #print(url_lst)
    #对链接进行格式化
    for i in url_lst:
        result = i.replace("\\", "").replace('"', "")
        if result not in new_list:
            if "t" not in result[8]:
                if "p" not in result[-2]:
                    new_list.append(result)
    #print(new_list)
    #print("共获得", len(new_list), "条链接")
    #获取单个订阅链接进行判断
    i = 1
    try:
        new_list_down = new_list[sub_n::]
    except:
        new_list_down = new_list[len(new_list) * 2 // 3::]
    #print("共获得", len(new_list_down), "条链接")
    #print('【判断链接是否为订阅链接】')
    for o in new_list_down:
        try:
            res = requests.get(o)
            #判断是否为clash
            try:
                skuid = re.findall('proxies:', res.text)[0]
                if skuid == "proxies:":
                    #print(i, ".这是个clash订阅", o)
                    end_list_clash.append(o)
            except:
                #判断是否为v2
                try:
                    #解密base64
                    peoxy = jiemi_base64(res.text)
                    #print(i, ".这是个v2ray订阅", o)
                    end_list_v2ray.append(o)
                    end_bas64.extend(peoxy.splitlines())
                    
                #均不是则非订阅链接
                except:
                    #print(i, ".非订阅链接")
                    pass
        except:
            #print("第", i, "个链接获取失败跳过！")
            pass
        i += 1
    return end_bas64

#写入文件
def write_document():
    if e_sub == [] or try_sub == []:
        print("订阅为空请检查！")
    else:
        #永久订阅
        random.shuffle(e_sub)
        for e in e_sub:
            try:
                res = requests.get(e)
                proxys=jiemi_base64(res.text)
                end_bas64.extend(proxys.splitlines())
            except:
                print(e,"永久订阅出现错误❌跳过")
        print('永久订阅更新完毕')
        #试用订阅
        random.shuffle(try_sub)
        for t in try_sub:
            try:
                res = requests.get(t)
                proxys=jiemi_base64(res.text)
                end_try.extend(proxys.splitlines())
            except Exception as er:
                print(t,"试用订阅出现错误❌跳过",er)
        print('试用订阅更新完毕',try_sub)
        #永久订阅去重
        end_bas64_A = list(set(end_bas64))
        print("去重完毕！！去除",len(end_bas64) - len(end_bas64_A),"个重复节点")
        #永久订阅去除多余换行符
        bas64 = '\n'.join(end_bas64_A).replace('\n\n', "\n").replace('\n\n', "\n").replace('\n\n', "\n")
        #试用去除多余换行符
        bas64_try = '\n'.join(end_try).replace('\n\n', "\n").replace('\n\n', "\n").replace('\n\n', "\n")
        #获取时间，给文档命名用
        t = time.localtime()
        date = time.strftime('%y%m', t)
        date_day = time.strftime('%y%m%d', t)
        #创建文件路径
        try:
            os.mkdir(f'{update_path}{date}')
        except FileExistsError:
            pass
        txt_dir = update_path + date + '/' + date_day + '.txt'
        #写入时间订阅
        file = open(txt_dir, 'w', encoding='utf-8')
        file.write(bas64)
        file.close()       
        
        #减少获取的个数
        r = 1
        length = len(end_bas64_A)  # 总长
        m = 8  # 切分成多少份
        step = int(length / m) + 1  # 每份的长度
        for i in range(0, length, step):
            print("起",i,"始",i+step)
            zhengli = '\n'.join(end_bas64_A[i: i + step]).replace('\n\n', "\n").replace('\n\n', "\n").replace('\n\n', "\n")
            #将获得的节点变成base64加密，为了长期订阅
            obj = base64.b64encode(zhengli.encode())
            plaintext_result = obj.decode()
            #写入长期订阅
            file_L = open("Long_term_subscription"+str(r), 'w', encoding='utf-8')
            file_L.write(plaintext_result)
            r += 1
        #写入总长期订阅
        obj = base64.b64encode(bas64.encode())
        plaintext_result = obj.decode()
        file_L = open("Long_term_subscription_num", 'w', encoding='utf-8')
        file_L.write(plaintext_result)
        #写入试用订阅
        obj_try = base64.b64encode(bas64_try.encode())
        plaintext_result_try = obj_try.decode()
        file_L_try = open("Long_term_subscription_try", 'w', encoding='utf-8')
        file_L_try.write(plaintext_result_try)
        #写入README
        with open("README.md", 'r', encoding='utf-8') as f:
            lines = f.readlines()
            f.close()
        now_time = datetime.datetime.now()
        TimeDate = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        for index in range(len(lines)):
            try:
                if lines[index] == '`https://raw.bgithub.xyz/w1770946466/Auto_proxy/main/Long_term_subscription_num`\n':
                    lines.pop(index+1)
                    lines.insert(index+1, f'`Total number of merge nodes: {length}`\n')
                if lines[index] == '`https://raw.bgithub.xyz/w1770946466/Auto_proxy/main/Long_term_subscription1`\n':
                    lines.pop(index+1)
                    lines.insert(index+1, f'`Total number of merge nodes: {step}`\n')
                if lines[index] == '`https://raw.bgithub.xyz/w1770946466/Auto_proxy/main/Long_term_subscription2`\n': # 目标行内容
                    lines.pop(index+1)
                    lines.insert(index+1, f'`Total number of merge nodes: {step}`\n')
                if lines[index] == '`https://raw.bgithub.xyz/w1770946466/Auto_proxy/main/Long_term_subscription3`\n': # 目标行内容
                    lines.pop(index+1)
                    lines.insert(index+1, f'`Total number of merge nodes: {step}`\n')
                if lines[index] == '`https://raw.bgithub.xyz/w1770946466/Auto_proxy/main/Long_term_subscription4`\n': # 目标行内容
                    lines.pop(index+1)
                    lines.insert(index+1, f'`Total number of merge nodes: {step}`\n')
                if lines[index] == '`https://raw.bgithub.xyz/w1770946466/Auto_proxy/main/Long_term_subscription5`\n': # 目标行内容
                    lines.pop(index+1)
                    lines.insert(index+1, f'`Total number of merge nodes: {step}`\n')
                if lines[index] == '`https://raw.bgithub.xyz/w1770946466/Auto_proxy/main/Long_term_subscription6`\n': # 目标行内容
                    lines.pop(index+1)
                    lines.insert(index+1, f'`Total number of merge nodes: {step}`\n')
                if lines[index] == '`https://raw.bgithub.xyz/w1770946466/Auto_proxy/main/Long_term_subscription7`\n': # 目标行内容
                    lines.pop(index+1)
                    lines.insert(index+1, f'`Total number of merge nodes: {step}`\n')
                if lines[index] == '`https://raw.bgithub.xyz/w1770946466/Auto_proxy/main/Long_term_subscription8`\n': # 目标行内容
                    lines.pop(index+1)
                    lines.insert(index+1, f'`Total number of merge nodes: {length-step*7}`\n')
                if lines[index] == '`https://raw.bgithub.xyz/w1770946466/Auto_proxy/main/Long_term_subscription3.yaml`\n': # 目标行内容
                    lines.pop(index+4)
                    lines.pop(index+4)
                    lines.insert(index+4, f'Updata：`{TimeDate}`\n')
                    lines.insert(index+4, f'### Try the number of high-speed subscriptions: `{len(try_sub)}`\n')
                if lines[index] == '>Trial subscription：\n': # 目标行内容
                    lines.pop(index)
                    lines.pop(index)
                """
                if lines[index] == '## ✨Star count\n': # 目标行内容
                    n = 5
                    for TrySub in try_sub:
                        lines.insert(index-n, f'\n>Trial subscription：\n`{TrySub}`\n')
                        n += 3
                """
            except:
                #print("写入READ出错")
                pass
        #写入试用订阅
        for index in range(len(lines)):
            try:
                if lines[index] == '## ✨Star count\n': # 目标行内容
                    n = 5
                    for TrySub in try_sub:
                        #lines.insert(index+n-1, f'\n>')
                        lines.insert(index-n, f'\n>Trial subscription：\n`{TrySub}`\n')
                        n += 3
            except:
                print("写入试用出错")
        
        with open("README.md", 'w', encoding='utf-8') as f:
            data = ''.join(lines)
            f.write(data)
        print("合并完成✅")
        try:
            numbers =sum(1 for _ in open(txt_dir))
            print("共获取到",numbers,"节点")
        except:
            print("出现错误！")
        
    return

#获取clash订阅
def get_yaml():
    print("开始获取clsah订阅")
    urls = []
    n = 1
    for i in urls:
        response = requests.get(i)
        #print(response.text)
        file_L = open("Long_term_subscription" + str(n) +".yaml", 'w', encoding='utf-8')
        file_L.write(response.text)
        file_L.close()
        n += 1
    print("clash订阅获取完成！")

#获取机场试用订阅
def get_sub_url():
    V2B_REG_REL_URL = '/api/v1/passport/auth/register'
    times = 1
    for current_url in home_urls:
        i = 0
        while i < times:
            header = {
                'Referer': current_url,
                'User-Agent': 'Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1',
                'Content-Type': 'application/x-www-form-urlencoded',
            }
            form_data = {
                'email': ''.join(random.choice(string.ascii_letters+string.digits) for _ in range(12))+'@gmail.com',
                'password': 'autosub_v2b',
                'invite_code': '',
                'email_code': ''
            }
            if current_url == 'https://xn--4gqu8thxjfje.com' or current_url == 'https://seeworld.pro'  or current_url == 'https://www.jwckk.top'or current_url == 'https://vvtestatiantian.top':
                try:
                    fan_res = requests.post(
                        f'{current_url}/api/v1/passport/auth/register', data=form_data, headers=header)
                    auth_data = fan_res.json()["data"]["auth_data"]
                    #print(auth_data)
                    fan_header = {
                        'Origin': current_url,
                        'Authorization': ''.join(auth_data),
                        'Content-Type': 'application/x-www-form-urlencoded',
                        'Connection': 'keep-alive',
                        'User-Agent': 'Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1',
                        'Referer': current_url,
                    }
                    fan_data = {
                        'period': 'onetime_price',
                        'plan_id': '1',
                    }
                    fan_res_n = requests.post(
                        f'{current_url}/api/v1/user/order/save', headers=fan_header, data=fan_data)
                    #print(fan_res_n.json()["data"])
                    fan_data_n = {
                        'trade_no':fan_res_n.json()["data"],
                        #'method': '1',
                    }
                    fan_res_pay = requests.post(
                        f'{current_url}/api/v1/user/order/checkout', data=fan_data_n, headers=fan_header)
                    subscription_url = f'{current_url}/api/v1/client/subscribe?token={fan_res.json()["data"]["token"]}'
                    try_sub.append(subscription_url)
                    e_sub.append(subscription_url)
                    print("add:"+subscription_url)
                except Exception as result:
                    print(result)
                    break
            else:
                try:
                    response = requests.post(
                        current_url+V2B_REG_REL_URL, data=form_data, headers=header)
                    subscription_url = f'{current_url}/api/v1/client/subscribe?token={response.json()["data"]["token"]}'
                    try_sub.append(subscription_url)
                    e_sub.append(subscription_url)
                    print("add:"+subscription_url)
                except Exception as e:
                    print("获取订阅失败",e)
            i += 1

            
  
def get_kkzui():
    # ========== 抓取 kkzui.com 的节点 ==========
    try:
        headers = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.53"}
        res = requests.get("https://kkzui.com/jd?orderby=modified",headers=headers)
        article_url = re.search(r'<h2 class="item-heading"><a href="(https://kkzui.com/(.*?)\.html)"',res.text).groups()[0]
        #print(article_url)
        res = requests.get(article_url,headers=headers)
        sub_url = re.search(r'<p><strong>这是v2订阅地址</strong>：(.*?)</p>',res.text).groups()[0]
        print(sub_url)
        e_sub.append(sub_url)
        print("获取kkzui.com完成！")
    except:
        print("获取kkzui.com失败！")
    try:
        headers = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.53"}
        res = requests.get("https://www.cfmem.com/search/label/free",headers=headers)
        article_url = re.search(r"https?://www\.cfmem\.com/\d{4}/\d{2}/\S+v2rayclash-vpn.html",res.text).group()
        #print(article_url)
        res = requests.get(article_url,headers=headers)
        sub_url = re.search(r'>v2ray订阅链接&#65306;(.*?)</span>',res.text).groups()[0]
        print(sub_url)
        try_sub.append(sub_url)
        e_sub.append(sub_url)
    except Exception as e:
        print(e)
        
    
if __name__ == '__main__':
    print("========== 开始获取机场订阅链接 ==========")
    get_sub_url()
    print("========== 开始获取kkzui.com订阅链接 ==========")
    get_kkzui()
    print("========== 开始获取频道订阅链接 ==========")
    for url in urls:
        #print(url, "开始获取......")
        thread = threading.Thread(target=get_content,args = (url,))
        thread.start()
        threads.append(thread)
        #resp = get_content(get_channel_http(url))
        #print(url, "获取完毕！！")
    #等待线程结束
    for t in tqdm(threads):
        t.join()
    print("========== 准备写入订阅 ==========")
    res = write_document()
    clash_sub = get_yaml()
    print("========== 写入完成任务结束 ==========")
